import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "DevLens 🔍",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <Suspense fallback={<Loading />}>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster richColors />
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
